### ISSUE TITLE
Script Fails When Search Criteria is Not One Word

### ISSUE THREAD

**Issue by BartTaylor** [ohmarchitect/clwatch#1]
If I try to put in a multi-word search, e.g. Standard Byke, the scripts breaks.

I'm running this via Cygwin (if that matters)

output from script:

./clwatch.sh: line 75: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 87: ${DIR}/${SEARCH_TERM}${LOCATION}_curr_list.txt: ambiguous redirect
./clwatch.sh: line 170: ${DIR}/${SEARCH_TERM}${LOCATION}_curr_list.txt: ambiguous redirect
./clwatch.sh: line 116: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 170: ${DIR}/${SEARCH_TERM}${LOCATION}_prev_list.txt: ambiguous redirect
./clwatch.sh: line 148: [: ...clwatch_files/'Standard: binary operator expected
mv: target "Byke'sfbay_prev_list.txt" is not a directory
./clwatch.sh: line 162: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 165: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 75: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 87: ${DIR}/${SEARCH_TERM}${LOCATION}_curr_list.txt: ambiguous redirect
./clwatch.sh: line 170: ${DIR}/${SEARCH_TERM}${LOCATION}_curr_list.txt: ambiguous redirect
./clwatch.sh: line 116: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 170: ${DIR}/${SEARCH_TERM}${LOCATION}_prev_list.txt: ambiguous redirect
./clwatch.sh: line 148: [: ...clwatch_files/'Standard: binary operator expected
mv: target "Byke'losangeles_prev_list.txt" is not a directory
./clwatch.sh: line 162: [: ...clwatch_files/'Standard: binary operator expected
./clwatch.sh: line 165: [: ...clwatch_files/'Standard: binary operator expected

**Comment by BartTaylor** [comment]
FYI - I've worked around this by using the '+' for the space between search terms. e.g. 'Standard+Byke' works.

**Comment by ohmarchitect** [comment]
Thanks for pointing that out!

I added the following lines to the script as an example:
   Multiple search term example(make sure to use a plus sign in-between search terms):
   echo red+ferrari >> ${DIR}/clwatch_search_terms_tmp.txt
